Repository ShootPointer/ShootPointer_BE, pull requests merged in 2025-09, with the labels that each got.

#62 🔗 chore : jacoco build.gradle 설정
  .gitignore
  build.gradle
Labels: 🔗 Chore

#63 test : github actions jacoco 동작 테스트
  build.gradle
Labels: 🔗 Chore, 👷 CI

#64 refact : DB 연관관계 @Builder.Default 로 수정 후 jacoco 테스트 재실행
  build.gradle
  gradlew
  lombok.config
  src/main/java/com/midas/shootpointer/domain/backnumber/entity/BackNumberEntity.java
  src/main/java/com/midas/shootpointer/domain/backnumber/mapper/BackNumberMapperImpl.java
  src/main/java/com/midas/shootpointer/domain/highlight/entity/HighlightEntity.java
  src/main/java/com/midas/shootpointer/domain/highlight/service/command/HighlightCommandService.java
  src/main/java/com/midas/shootpointer/domain/member/entity/Member.java
  src/main/resources/application-dev.yml
  src/main/resources/application-test.yml
  src/main/resources/application.yml
  src/test/java/com/midas/shootpointer/ShootpointerApplicationTests.java
  src/test/java/com/midas/shootpointer/domain/backnumber/mapper/BackNumberMapperImplTest.java
  src/test/java/com/midas/shootpointer/domain/highlight/repository/HighlightQueryRepositoryTest.java
  src/test/java/com/midas/shootpointer/domain/member/repository/MemberRepositoryTest.java
  src/test/java/com/midas/shootpointer/global/util/encrypt/EncryptConverterTest.java
  src/test/java/com/midas/shootpointer/global/util/jwt/JwtUtilTest.java
Labels: 👷 CI, ♻️ Refactor

#79 🛠️ Refactor : Post 도메인 아키텍처 리팩토링
  src/main/java/com/midas/shootpointer/domain/highlight/entity/HighlightEntity.java
  src/main/java/com/midas/shootpointer/domain/post/business/PostManager.java
  src/main/java/com/midas/shootpointer/domain/post/business/command/PostCommandService.java
  src/main/java/com/midas/shootpointer/domain/post/business/command/PostCommandServiceImpl.java
  src/main/java/com/midas/shootpointer/domain/post/controller/PostCommandController.java
  src/main/java/com/midas/shootpointer/domain/post/controller/test
  src/main/java/com/midas/shootpointer/domain/post/helper/PostHelperImpl.java
  src/main/java/com/midas/shootpointer/domain/post/helper/PostUtil.java
  src/main/java/com/midas/shootpointer/domain/post/helper/PostUtilImpl.java
  src/test/java/com/midas/shootpointer/domain/post/business/PostManagerTest.java
  src/test/java/com/midas/shootpointer/domain/post/business/command/PostCommandServiceImplTest.java
  src/test/java/com/midas/shootpointer/domain/post/controller/PostCommandControllerTest.java
  src/test/java/com/midas/shootpointer/domain/post/helper/PostHelperImplTest.java
  src/test/java/com/midas/shootpointer/domain/post/helper/PostUtilImplTest.java
Labels: ♻️ Refactor

#85 🌟 Feature : 게시물 단건 조회.
  src/main/java/com/midas/shootpointer/domain/like/controller/LikeController.java
  src/main/java/com/midas/shootpointer/domain/post/business/PostManager.java
  src/main/java/com/midas/shootpointer/domain/post/business/query/PostQueryService.java
  src/main/java/com/midas/shootpointer/domain/post/business/query/PostQueryServiceImpl.java
  src/main/java/com/midas/shootpointer/domain/post/controller/PostCommandController.java
  src/main/java/com/midas/shootpointer/domain/post/controller/PostQueryController.java
  src/main/java/com/midas/shootpointer/domain/post/dto/PostResponse.java
  src/main/java/com/midas/shootpointer/domain/post/dto/test
  src/main/java/com/midas/shootpointer/domain/post/helper/PostHelperImpl.java
  src/main/java/com/midas/shootpointer/domain/post/helper/PostUtil.java
  src/main/java/com/midas/shootpointer/domain/post/helper/PostUtilImpl.java
  src/main/java/com/midas/shootpointer/domain/post/mapper/PostMapper.java
  src/main/java/com/midas/shootpointer/domain/post/mapper/PostMapperImpl.java
  src/main/java/com/midas/shootpointer/domain/post/repository/PostQueryRepository.java
  src/main/resources/application-dev.yml
  src/main/resources/application-test.yml
  src/main/resources/application.yml
  src/test/java/com/midas/shootpointer/ShootpointerApplicationTests.java
  src/test/java/com/midas/shootpointer/domain/highlight/repository/HighlightQueryRepositoryTest.java
  src/test/java/com/midas/shootpointer/domain/like/business/LikeManagerTest.java
  src/test/java/com/midas/shootpointer/domain/like/controller/LikeControllerTest.java
  src/test/java/com/midas/shootpointer/domain/like/helper/LikeUtilImplTest.java
  src/test/java/com/midas/shootpointer/domain/like/repository/LikeQueryRepositoryTest.java
  src/test/java/com/midas/shootpointer/domain/post/business/query/PostQueryServiceImplTest.java
  src/test/java/com/midas/shootpointer/domain/post/controller/PostQueryControllerTest.java
  src/test/java/com/midas/shootpointer/domain/post/helper/PostUtilImplTest.java
  src/test/java/com/midas/shootpointer/domain/post/mapper/PostMapperImplTest.java
  src/test/java/com/midas/shootpointer/domain/post/repository/PostQueryRepositoryTest.java
  src/test/java/com/midas/shootpointer/global/util/jwt/JwtUtilTest.java
Labels: ✨ Feature

#96 🌟Feature : 게시물 다건 조회 구현
  src/main/java/com/midas/shootpointer/domain/highlight/entity/HighlightEntity.java
  src/main/java/com/midas/shootpointer/domain/post/business/PostManager.java
  src/main/java/com/midas/shootpointer/domain/post/business/PostOrderType.java
  src/main/java/com/midas/shootpointer/domain/post/business/command/PostCommandService.java
  src/main/java/com/midas/shootpointer/domain/post/business/command/PostCommandServiceImpl.java
  src/main/java/com/midas/shootpointer/domain/post/business/query/PostQueryService.java
  src/main/java/com/midas/shootpointer/domain/post/business/query/PostQueryServiceImpl.java
  src/main/java/com/midas/shootpointer/domain/post/controller/PostCommandController.java
  src/main/java/com/midas/shootpointer/domain/post/controller/PostQueryController.java
  src/main/java/com/midas/shootpointer/domain/post/dto/request/PostRequest.java
  src/main/java/com/midas/shootpointer/domain/post/dto/response/PostListResponse.java
  src/main/java/com/midas/shootpointer/domain/post/dto/response/PostResponse.java
  src/main/java/com/midas/shootpointer/domain/post/entity/PostEntity.java
  src/main/java/com/midas/shootpointer/domain/post/helper/PostHelperImpl.java
  src/main/java/com/midas/shootpointer/domain/post/helper/PostUtil.java
  src/main/java/com/midas/shootpointer/domain/post/helper/PostUtilImpl.java
  src/main/java/com/midas/shootpointer/domain/post/helper/PostValidation.java
  src/main/java/com/midas/shootpointer/domain/post/helper/PostValidationImpl.java
  src/main/java/com/midas/shootpointer/domain/post/mapper/PostMapper.java
  src/main/java/com/midas/shootpointer/domain/post/mapper/PostMapperImpl.java
  src/main/java/com/midas/shootpointer/domain/post/repository/PostCommandRepository.java
  src/main/java/com/midas/shootpointer/domain/post/repository/PostQueryRepository.java
  src/main/java/com/midas/shootpointer/global/common/ErrorCode.java
  src/test/java/com/midas/shootpointer/domain/like/business/LikeManagerConcurrencyTest.java
  src/test/java/com/midas/shootpointer/domain/like/business/LikeManagerTest.java
  src/test/java/com/midas/shootpointer/domain/post/business/PostManagerTest.java
  src/test/java/com/midas/shootpointer/domain/post/business/command/PostCommandServiceImplTest.java
  src/test/java/com/midas/shootpointer/domain/post/business/query/PostQueryServiceImplTest.java
  src/test/java/com/midas/shootpointer/domain/post/controller/PostCommandControllerTest.java
  src/test/java/com/midas/shootpointer/domain/post/controller/PostQueryControllerTest.java
  src/test/java/com/midas/shootpointer/domain/post/entity/PostEntityTest.java
  src/test/java/com/midas/shootpointer/domain/post/helper/PostHelperImplTest.java
  src/test/java/com/midas/shootpointer/domain/post/helper/PostUtilImplTest.java
  src/test/java/com/midas/shootpointer/domain/post/helper/PostUtilImplTestOnlyQuery.java
  src/test/java/com/midas/shootpointer/domain/post/mapper/PostMapperImplTest.java
  src/test/java/com/midas/shootpointer/domain/post/repository/PostQueryRepositoryTest.java
Labels: ✨ Feature, ✅ Test

#110 🧩 Fix : 로그인/회원가입 시 발생하는 Refresh Token 갱신 버그 수정
  src/main/java/com/midas/shootpointer/domain/member/business/command/TokenServiceImpl.java
  src/main/java/com/midas/shootpointer/global/util/jwt/handler/JwtHandlerImpl.java
Labels: 🐛 BugFix

#112 🧩 Fix : 회원탈퇴 시 발생한 Refresh Token 버그 수정
  src/main/java/com/midas/shootpointer/domain/member/business/command/MemberCommandService.java
  src/main/java/com/midas/shootpointer/domain/member/business/command/MemberCommandServiceImpl.java
  src/main/java/com/midas/shootpointer/domain/member/controller/MemberQueryController.java
Labels: 🐛 BugFix

#113 🌟 Feature : 커뮤니티 검색 기능 구현
  build.gradle
  src/main/java/com/midas/shootpointer/domain/backnumber/controller/BackNumberController.java
  src/main/java/com/midas/shootpointer/domain/like/controller/LikeController.java
  src/main/java/com/midas/shootpointer/domain/post/business/PostManager.java
  src/main/java/com/midas/shootpointer/domain/post/business/query/PostQueryService.java
  src/main/java/com/midas/shootpointer/domain/post/business/query/PostQueryServiceImpl.java
  src/main/java/com/midas/shootpointer/domain/post/controller/PostCommandController.java
  src/main/java/com/midas/shootpointer/domain/post/controller/PostQueryController.java
  src/main/java/com/midas/shootpointer/domain/post/helper/PostHelperImpl.java
  src/main/java/com/midas/shootpointer/domain/post/helper/PostUtil.java
  src/main/java/com/midas/shootpointer/domain/post/helper/PostUtilImpl.java
  src/main/java/com/midas/shootpointer/domain/post/repository/PostQueryRepository.java
  src/main/java/com/midas/shootpointer/global/security/SecurityUtils.java
  src/test/java/com/midas/shootpointer/WithMockCustomMember.java
  src/test/java/com/midas/shootpointer/WithMockCustomUserSecurityContextFactory.java
  src/test/java/com/midas/shootpointer/domain/backnumber/controller/BackNumberControllerTest.java
  src/test/java/com/midas/shootpointer/domain/like/controller/LikeControllerTest.java
  src/test/java/com/midas/shootpointer/domain/like/helper/LikeUtilImplTest.java
  src/test/java/com/midas/shootpointer/domain/post/business/PostManagerTest.java
  src/test/java/com/midas/shootpointer/domain/post/business/query/PostQueryServiceImplTest.java
  src/test/java/com/midas/shootpointer/domain/post/controller/PostCommandControllerTest.java
  src/test/java/com/midas/shootpointer/domain/post/controller/PostQueryControllerTest.java
  src/test/java/com/midas/shootpointer/domain/post/helper/PostHelperImplTest.java
  src/test/java/com/midas/shootpointer/domain/post/helper/PostUtilImplTest.java
  src/test/java/com/midas/shootpointer/domain/post/repository/PostQueryRepositoryTest.java
Labels: ✨ Feature

#125 🌟 Feature : 게시물 검색 정확도 향상 - Elasticsearch 활용
  .gitignore
  Dockerfile
  Dockerfile.elesticsearch
  build.gradle
  docker-compose.yml
  src/main/java/com/midas/shootpointer/ShootpointerApplication.java
  src/main/java/com/midas/shootpointer/domain/backnumber/Simple.java
  src/main/java/com/midas/shootpointer/domain/like/business/LikeManager.java
  src/main/java/com/midas/shootpointer/domain/post/business/PostManager.java
  src/main/java/com/midas/shootpointer/domain/post/business/query/PostQueryService.java
  src/main/java/com/midas/shootpointer/domain/post/business/query/PostQueryServiceImpl.java
  src/main/java/com/midas/shootpointer/domain/post/controller/PostQueryController.java
  src/main/java/com/midas/shootpointer/domain/post/entity/PostDocument.java
  src/main/java/com/midas/shootpointer/domain/post/entity/PostEntity.java
  src/main/java/com/midas/shootpointer/domain/post/helper/PostHelper.java
  src/main/java/com/midas/shootpointer/domain/post/helper/elastic/PostElasticSearchHelper.java
  src/main/java/com/midas/shootpointer/domain/post/helper/elastic/PostElasticSearchHelperImpl.java
  src/main/java/com/midas/shootpointer/domain/post/helper/elastic/PostElasticSearchUtil.java
  src/main/java/com/midas/shootpointer/domain/post/helper/elastic/PostElasticSearchUtilImpl.java
  src/main/java/com/midas/shootpointer/domain/post/helper/simple/PostHelper.java
  src/main/java/com/midas/shootpointer/domain/post/helper/simple/PostHelperImpl.java
  src/main/java/com/midas/shootpointer/domain/post/helper/simple/PostUtil.java
  src/main/java/com/midas/shootpointer/domain/post/helper/simple/PostUtilImpl.java
  src/main/java/com/midas/shootpointer/domain/post/helper/simple/PostValidation.java
  src/main/java/com/midas/shootpointer/domain/post/helper/simple/PostValidationImpl.java
  src/main/java/com/midas/shootpointer/domain/post/mapper/PostElasticSearchMapper.java
  src/main/java/com/midas/shootpointer/domain/post/mapper/PostElasticSearchMapperImpl.java
  src/main/java/com/midas/shootpointer/domain/post/mapper/PostMapper.java
  src/main/java/com/midas/shootpointer/domain/post/mapper/PostMapperImpl.java
  src/main/java/com/midas/shootpointer/domain/post/repository/PostElasticSearchRepository.java
  src/main/java/com/midas/shootpointer/domain/post/repository/PostQueryRepository.java
  src/main/java/com/midas/shootpointer/global/config/ElasticSearchConfig.java
  src/main/java/com/midas/shootpointer/global/entity/BaseEntity.java
  src/main/java/com/midas/shootpointer/test/DummyDataLoader.java
  src/main/java/com/midas/shootpointer/test/SetRealPostDataLoader.java
  src/main/resources/application-dev.yml
  src/main/resources/application.yml
  src/main/resources/documents_clean.json
  src/main/resources/elasticsearch/post-mapping.json
  src/main/resources/elasticsearch/post-setting.json
  src/test/java/com/midas/shootpointer/config/TestElasticSearchConfig.java
  src/test/java/com/midas/shootpointer/domain/backnumber/business/BackNumberManagerTest.java
  src/test/java/com/midas/shootpointer/domain/backnumber/controller/BackNumberControllerTest.java
  src/test/java/com/midas/shootpointer/domain/backnumber/helper/BackNumberUtilImplTest.java
  src/test/java/com/midas/shootpointer/domain/like/business/LikeManagerConcurrencyTest.java
  src/test/java/com/midas/shootpointer/domain/like/business/LikeManagerTest.java
  src/test/java/com/midas/shootpointer/domain/like/controller/LikeControllerTest.java
  src/test/java/com/midas/shootpointer/domain/like/helper/LikeUtilImplTest.java
  src/test/java/com/midas/shootpointer/domain/like/repository/LikeQueryRepositoryTest.java
  src/test/java/com/midas/shootpointer/domain/post/business/PostManagerTest.java
  src/test/java/com/midas/shootpointer/domain/post/controller/PostCommandControllerTest.java
  src/test/java/com/midas/shootpointer/domain/post/helper/PostHelperImplTest.java
  src/test/java/com/midas/shootpointer/domain/post/helper/PostUtilImplTest.java
  src/test/java/com/midas/shootpointer/domain/post/helper/PostUtilImplTestOnlyQuery.java
  src/test/java/com/midas/shootpointer/domain/post/helper/PostValidationImplTest.java
  src/test/java/com/midas/shootpointer/domain/post/repository/PostQueryRepositoryTest.java
  src/test/java/com/midas/shootpointer/global/util/jwt/JwtUtilTest.java
  true) 처리
Labels: ✨ Feature
