Repository ShootPointer/ShootPointer_BE, pull requests merged in 2025-06, with the labels that each got.

#29 ⭐️Feature : 등 번호 엔티티 생성 및 매핑, 등 번호 등록 서비스 구현
  Dockerfile
  Jenkinsfile
  build.gradle
  docker-compose.yml
  src/main/java/com/midas/shootpointer/adapter/in/web/HealthCheckController.java
  src/main/java/com/midas/shootpointer/domain/backnumber/controller/BackNumberController.java
  src/main/java/com/midas/shootpointer/domain/backnumber/dto/BackNumberRequest.java
  src/main/java/com/midas/shootpointer/domain/backnumber/dto/BackNumberResponse.java
  src/main/java/com/midas/shootpointer/domain/backnumber/entity/BackNumber.java
  src/main/java/com/midas/shootpointer/domain/backnumber/entity/BackNumberEntity.java
  src/main/java/com/midas/shootpointer/domain/backnumber/mapper/BackNumberMapper.java
  src/main/java/com/midas/shootpointer/domain/backnumber/mapper/BackNumberMapperImpl.java
  src/main/java/com/midas/shootpointer/domain/backnumber/repository/BackNumberRepository.java
  src/main/java/com/midas/shootpointer/domain/backnumber/service/BackNumberService.java
  src/main/java/com/midas/shootpointer/domain/backnumber/service/BackNumberServiceImpl.java
  src/main/java/com/midas/shootpointer/domain/community/test.java
  src/main/java/com/midas/shootpointer/domain/highlight/entity/HighlightEntity.java
  src/main/java/com/midas/shootpointer/domain/highlight/mapper/HighlightMapper.java
  src/main/java/com/midas/shootpointer/domain/highlight/repository/HighlightFetchRepository.java
  src/main/java/com/midas/shootpointer/domain/highlight/repository/HighlightRepository.java
  src/main/java/com/midas/shootpointer/domain/highlight/repository/HighlightSelectRepository.java
  src/main/java/com/midas/shootpointer/domain/member/entity/Member.java
  src/main/java/com/midas/shootpointer/domain/member/repository/MemberRepository.java
  src/main/java/com/midas/shootpointer/domain/memberbacknumber/entity/MemberBackNumberEntity.java
  src/main/java/com/midas/shootpointer/domain/memberbacknumber/repository/MemberBackNumberRepository.java
  src/main/java/com/midas/shootpointer/global/common/ErrorCode.java
  src/main/java/com/midas/shootpointer/global/util/file/FileType.java
  src/main/java/com/midas/shootpointer/global/util/file/GenerateFileName.java
  src/main/java/com/midas/shootpointer/global/util/jwt/JwtUtil.java
  src/main/java/com/midas/shootpointer/global/util/uuid/UUIDHandler.java
  src/main/java/com/midas/shootpointer/global/util/uuid/UUIDHandlerImpl.java
  src/main/java/com/midas/shootpointer/infrastructure/openCV/OpenCVClient.java
  src/main/java/com/midas/shootpointer/infrastructure/openCV/OpenCVClientImpl.java
  src/main/resources/application-dev.yml
  src/main/resources/application.yml
  src/main/resources/docker-compose.yml
  src/test/java/com/midas/shootpointer/domain/backnumber/mapper/BackNumberMapperImplTest.java
  src/test/java/com/midas/shootpointer/global/util/file/GenerateFileNameTest.java
  src/test/java/com/midas/shootpointer/infrastructure/openCV/OpenCVClientTest.java
Labels: ✨ Feature

#34 🐞 Bug : Redis Connection Refused issue 해결
  src/main/java/com/midas/shootpointer/domain/member/service/RefreshTokenService.java
  src/main/java/com/midas/shootpointer/global/config/RedisConfig.java
  src/main/java/com/midas/shootpointer/infrastructure/openCV/OpenCVClientImpl.java
Labels: 🐛 BugFix

#35 🧪Test : BackNumber-service Test Code
  .gitignore
  build.gradle
  src/main/java/com/midas/shootpointer/domain/backnumber/controller/BackNumberController.java
  src/main/java/com/midas/shootpointer/domain/backnumber/dto/BackNumberRequest.java
  src/main/java/com/midas/shootpointer/domain/backnumber/entity/BackNumber.java
  src/main/java/com/midas/shootpointer/domain/backnumber/service/BackNumberServiceImpl.java
  src/main/java/com/midas/shootpointer/domain/community/test.java
  src/main/java/com/midas/shootpointer/global/common/ErrorCode.java
  src/main/java/com/midas/shootpointer/infrastructure/openCV/OpenCVClient.java
  src/main/java/com/midas/shootpointer/infrastructure/openCV/OpenCVClientImpl.java
  src/main/java/com/midas/shootpointer/infrastructure/openCV/OpenCVProperties.java
  src/main/java/com/midas/shootpointer/infrastructure/openCV/dto/OpenCVResponse.java
  src/main/java/com/midas/shootpointer/infrastructure/openCV/service/OpenCVClient.java
  src/main/java/com/midas/shootpointer/infrastructure/openCV/service/OpenCVClientImpl.java
  src/main/java/com/midas/shootpointer/infrastructure/test.java
  src/main/resources/application-dev.yml
  src/main/resources/application-test.yml
  src/test/java/com/midas/shootpointer/domain/backnumber/controller/BackNumberControllerTest.java
  src/test/java/com/midas/shootpointer/domain/backnumber/service/BackNumberServiceImplTest.java
  src/test/java/com/midas/shootpointer/infrastructure/openCV/OpenCVClientTest.java
Labels: ✅ Test, ♻️ Refactor

#38 🛠️ Refactor : Member Id Type Long -> UUID 변환
  src/main/java/com/midas/shootpointer/domain/backnumber/service/BackNumberServiceImpl.java
  src/main/java/com/midas/shootpointer/domain/highlight/entity/HighlightEntity.java
  src/main/java/com/midas/shootpointer/domain/member/dto/KakaoDTO.java
  src/main/java/com/midas/shootpointer/domain/member/entity/Member.java
  src/main/java/com/midas/shootpointer/domain/member/repository/MemberRepository.java
  src/main/java/com/midas/shootpointer/domain/member/service/KakaoService.java
  src/main/java/com/midas/shootpointer/domain/memberbacknumber/entity/MemberBackNumberEntity.java
  src/main/java/com/midas/shootpointer/global/common/ErrorCode.java
  src/main/java/com/midas/shootpointer/global/util/jwt/JwtUtil.java
  src/main/resources/application-dev.yml
  src/test/java/com/midas/shootpointer/domain/backnumber/service/BackNumberServiceImplTest.java
Labels: ♻️ Refactor

#42 🚨 Hotfix : getMemberId()에 token 파라미터 추가
  src/main/java/com/midas/shootpointer/domain/admin/AdminService.java
  src/main/java/com/midas/shootpointer/domain/admin/AdminTokenController.java
  src/main/java/com/midas/shootpointer/domain/admin/AdminTokenProvider.java
  src/main/java/com/midas/shootpointer/domain/backnumber/controller/BackNumberController.java
  src/main/java/com/midas/shootpointer/domain/backnumber/service/BackNumberService.java
  src/main/java/com/midas/shootpointer/domain/backnumber/service/BackNumberServiceImpl.java
  src/main/java/com/midas/shootpointer/global/util/jwt/JwtUtil.java
  src/test/java/com/midas/shootpointer/domain/backnumber/controller/BackNumberControllerTest.java
  src/test/java/com/midas/shootpointer/domain/backnumber/service/BackNumberServiceImplTest.java
Labels: 🚑 Hotfix

#44 🚨 Hotfix : Kakao 로그인 후 AccessToken에 저장된 memberId와 DB에 Builder를 통해 저장되는 memberId 불일치 버그 수정
  src/main/java/com/midas/shootpointer/domain/admin/AdminTokenProvider.java
  src/main/java/com/midas/shootpointer/domain/member/service/KakaoService.java
  src/main/java/com/midas/shootpointer/global/util/jwt/JwtUtil.java
  src/test/java/com/midas/shootpointer/global/util/jwt/JwtUtilTest.java
Labels: 🐛 BugFix, 🚑 Hotfix

#54 🚨 Hotfix : Kakao Access Token Loging
  src/main/java/com/midas/shootpointer/domain/member/service/KakaoService.java
Labels: 🚑 Hotfix

#55 🚨 Hotfix : Kakao Access Token Loging
  src/main/java/com/midas/shootpointer/domain/backnumber/entity/BackNumber.java
  src/main/java/com/midas/shootpointer/domain/member/service/KakaoService.java
Labels: 🚑 Hotfix

#56 🚨 Hotfix : Kakao Access Token 에러 로깅과 중복 요청 방지 로직 추가
  src/main/java/com/midas/shootpointer/domain/member/controller/KakaoController.java
  src/main/java/com/midas/shootpointer/domain/member/service/KakaoService.java
  src/main/java/com/midas/shootpointer/global/common/ErrorCode.java
Labels: 🚑 Hotfix
